### ISSUE TITLE
Build fail: Undeclared InputKeyMAX

### ISSUE THREAD

**Issue by ase1590** [quen0n/FipperZero-DHT-Monitor#1]
The following error occurs on build with Official firmware 0.7

```
CC      applications/plugins/FipperZero-DHT-Monitor-1.1/quenon_dht_mon.c
applications/plugins/FipperZero-DHT-Monitor-1.1/quenon_dht_mon.c: In function 'quenon_dht_mon_app':
applications/plugins/FipperZero-DHT-Monitor-1.1/quenon_dht_mon.c:437:26: error: 'InputKeyMAX' undeclared (first use in this function); did you mean 'InputKey'?
  437 |                     case InputKeyMAX:
      |                          ^~~~~~~~~~~
      |                          InputKey

```

**Comment by ase1590** [comment]
Also of note, against official when compiled after taking out InputKeyMax, FBT reports the following:

`quenon_dht_mon.fap: app won't run. Unresolved symbols: {'strtok'}`

**Comment by quen0n** [comment]
On the latest version of the official firmware, I could not reproduce the bug with InputKeyMAX. Problems with {'strcat', 'strtok'} will be solved in the new version of the plugin

Thank you for your message.

**Comment by ase1590** [comment]
It looks like my issue is only reproducible when checking out `release` and compiling against release firmware. 

The issue does not present itself against `dev` branch, so I'm going to say this can be closed as this issue will eventually be solved upstream as it makes it way official release

**Comment by quen0n** [comment]
https://github.com/quen0n/FipperZero-DHT-Monitor/releases/tag/v1.1owf
